# Generated by Django 5.2.8 on 2025-11-18 19:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0001_initial'),
        ('credentials', '0002_credentialsmodel_delete_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEventModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida')], max_length=5)),
                ('access_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.accesspoint')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events', to='credentials.credentialsmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='AccessEvent',
        ),
    ]
