# Generated by Django 5.2.8 on 2025-11-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('UsersID', models.CharField(max_length=10, unique=True)),
                ('Password', models.CharField(max_length=10)),
                ('Role', models.CharField(choices=[('admin', 'Administrador'), ('vigilante', 'Vigilante')], default='vigilante', max_length=10)),
            ],
        ),
    ]
