# Generated by Django 5.2.8 on 2025-11-22 22:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accesscontrol', '0002_accesseventmodels_delete_accessevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_by', models.CharField(choices=[('HORA', 'Hora'), ('ESTADO', 'Estado de acceso')], max_length=10)),
                ('hour_from', models.TimeField(blank=True, null=True)),
                ('hour_to', models.TimeField(blank=True, null=True)),
                ('estado_acceso', models.CharField(blank=True, max_length=5, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_events', models.PositiveIntegerField(default=0)),
                ('events', models.ManyToManyField(related_name='reports', to='accesscontrol.accesseventmodels')),
            ],
        ),
    ]
