# Generated by Django 5.2.8 on 2025-11-18 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_code', models.CharField(blank=True, editable=False, max_length=6, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('restricted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.visitor')),
            ],
        ),
        migrations.DeleteModel(
            name='Credentials',
        ),
    ]
